name: VERGATARIO
favicon: null
layout_spectrum: 0.16167981689795852
typography_spectrum: 0.9427493619732559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#48c5f1'
    - '#fb3b48'
    - '#1673b9'
    - '#350d0d'
  brandStrength: 0.9375
  lightness: 0.9604663574136794
  saturation: 0.39720071922056377
  rhythmicContrast: 0.532854036660865
purpose: []
